### ISSUE TITLE
Android UI VF Issues

### ISSUE THREAD

**Issue by simoncozens** [notofonts/malayalam#18]
Android requires a "UI build" of Noto Sans Malayalam, delivered as a slim variable font. We can't currently build the UI VFs from the Glyphs sources directly - the UI styles is defined as a set of instances with various magical custom parameters to re-encode glyphs, replace features, and transform the glyph outlines. We do have a way to hotfix the ordinary VF into the UI VF, but it's a horrible (and manual) process.

The process needs to become more robust, automated, and tested. Current issues on the previous build:

Name tables need updating
I ran the hotfixer on the full-range VF instead of the slim VF.

**Comment by simoncozens** [comment]
These UI VFs are now generated through the CI. Link to development version here:
https://notofonts.github.io/malayalam/fonts/NotoSansMalayalam/unhinted/slim-variable-ttf/NotoSansMalayalam-UI-VF.ttf

**Comment by chrissimpkins** [comment]
Fixed. Thank you very much Simon
