### ISSUE TITLE
U10 Traditional Conjuncts?

### ISSUE THREAD

**Issue by davelab6** [notofonts/malayalam#27]
In b/71567577 @cibu said in 2018, 

> Please add glyphs and update the tables to produce traditional conjuncts as per the unicode standard version 10.0, Section 12.9, Page 505.

@cibu @simoncozens do you know if this was done already for both fonts?

**Comment by simoncozens** [comment]
We do *not* support the traditional forms and would need them to be drawn.

**Comment by simoncozens** [comment]
Just realised this is the same as #1.
